services:

  postgresql:
    image: postgres:latest
    container_name: edumate_postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edumate

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: edumate_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgresql
    networks:
      - edumate

  minio:
    image: minio/minio:latest
    container_name: edumate_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    ports:
      - "${MINIO_PORT}:9000"
    volumes:
      - minio_data:/data
    networks:
      - edumate

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: edumate_keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - edumate

  nginx:
    image: nginx:latest
    container_name: edumate_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_URL=http://edumate_keycloak:8080
    networks:
      - edumate

  qdrant:
    image: qdrant/qdrant:latest
    container_name: edumate_qdrant
    environment:
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - default

  student-data-service:
    container_name: edumate_student
    build: ./services/student-data/
    depends_on: 
      - "postgresql"
    ports:
      - "8001:3000"
    env_file: .env
    networks:
      - edumate

  material-service:
    container_name: edumate_material
    build: ./services/material
    depends_on: 
      - postgresql
    ports:
      - "8002:3000"
    env_file: .env
    networks:
      - edumate

  evaluation-service:
    container_name: edumate_evaluation
    build: ./services/evaluation/
    depends_on: 
      - postgresql
    ports:
      - "8003:8000"
    env_file: .env
    networks:
      - edumate

  multi-modal-rag-service:
    container_name: edumate_multi_modal_rag
    build: ./services/multi-modal-rag/
    depends_on: 
      - qdrant 
    ports:
      - "8004:8000"
    env_file: .env
    networks:
      - edumate

  wq-correction-service:
    container_name: edumate_correction
    build: ./services/wq-correction/
    ports:
      - "8005:8000"
    env_file: .env
    networks:
      - edumate

  transcription-service:
    container_name: edumate_transcription
    build: ./services/transcription/
    ports:
      - "8006:8000"
    networks:
      - edumate

volumes:
  postgres_data:
  minio_data:
  keycloak_data:
  qdrant_data:

networks:
  edumate:
    driver: bridge
